#쇼핑몰 프로젝트 테이블

#1. 쇼핑몰 회원 테이블
CREATE TABLE SHOP_MEMBER (
	MEM_ID VARCHAR(20) PRIMARY KEY
	, MEM_PW VARCHAR(20) NOT NULL
	, MEM_NAME VARCHAR(10) NOT NULL
	, MEM_TEL VARCHAR(20) NOT NULL UNIQUE #010-1111-2222
	, MEM_ADDR VARCHAR(30)
	, ADDR_DETAIL VARCHAR(30)
	, GENDER VARCHAR(6) NOT NULL #'male', 'female'
	, MEM_ROLE VARCHAR(10) NOT NULL DEFAULT 'USER' #'USER', 'ADMIN'
	, STATUS VARCHAR(10) DEFAULT 'ACTIVE' #'ACTIVE' 'DEACTIVE' = 탈퇴
	, JOIN_DATE DATETIME DEFAULT SYSDATE()
);

DROP TABLE SHOP_MEMBER;

SELECT * FROM SHOP_MEMBER;

SELECT
	MEM_ID
FROM SHOP_MEMBER
WHERE MEM_ID = 'java';

#2. 도서 카테고리 테이블
CREATE TABLE BOOK_CATEGORY(
	CATEGORY_NO INT PRIMARY KEY AUTO_INCREMENT
	, CATEGORY_NAME VARCHAR(30) NOT NULL 
);

INSERT INTO BOOK_CATEGORY VALUES(1, 'IT/인터넷');
INSERT INTO BOOK_CATEGORY VALUES(2, '소설/에세이');
INSERT INTO BOOK_CATEGORY VALUES(3, '자기계발');

SELECT * FROM BOOK_CATEGORY;

#3. 도서  테이블
CREATE TABLE SHOP_BOOK(
	BOOK_NO INT PRIMARY KEY AUTO_INCREMENT
	, BOOK_NAME VARCHAR(30) NOT NULL
	, AUTHOR VARCHAR(20) NOT NULL
	, BOOK_PRICE INT NOT NULL
	, STOCK INT NOT NULL
	, BOOK_INFO VARCHAR(100) NOT NULL
	, CATEGORY_NO INT NOT NULL REFERENCES BOOK_CATEGORY(CATEGORY_NO)
);	
SELECT * FROM SHOP_BOOK;

DROP TABLE shop_book;

    SELECT
      CATEGORY_NO
      , CATEGORY_NAME
    FROM BOOK_CATEGORY;

#4. 도서 이미지 테이블
