#---------------------게시판 프로젝트 관련 테이블---------------------
#주요기능
#게시글 CRUD
#검색 기능
#페이지 네이션
#로그인 + 관리자 기능  -> 권한처리
#댓글 (추가, 삭제, 목록 조회)

DROP TABLE BOARD_MEMBER;

#게시글 커뮤니티 회원정보
CREATE TABLE BOARD_MEMBER(
	MEM_ID VARCHAR(20) PRIMARY KEY
	, MEM_PW VARCHAR(20) NOT NULL
	, MEM_NAME VARCHAR(20) NOT NULL
	, MEM_ROLE VARCHAR(10) NOT NULL DEFAULT 'USER' #회원권한(USER, ADMIN)
	, JOIN_DATE DATETIME DEFAULT SYSDATE()
);

#게시글 테이블
CREATE TABLE BOARD(
	BOARD_NUM INT PRIMARY KEY AUTO_INCREMENT
	, TITLE VARCHAR(20) NOT NULL 
	, CONTENT VARCHAR(20)
	, WRITER VARCHAR(20) NOT NULL REFERENCES BOARD_MEMBER(MEM_ID)   #외래키제약조건(NOT NULL도 필수~~~~)
	, READ_CNT INT DEFAULT 0 
	, CREATE_DATE DATETIME DEFAULT SYSDATE()
);

#댓글 정보 테이블  (게시글에 달린 댓글이니까 글과 연결도 되어야한다!)
CREATE TABLE BOARD_REPLY(
	REPLY_NUM INT PRIMARY KEY AUTO_INCREMENT
	, REPLY_CONTNET VARCHAR(30) NOT NULL
	, REPLY_WRITER VARCHAR(20) NOT NULL REFERENCES BOARD_MEMBER(MEM_ID)
	, REPLY_CREATE_DATE DATETIME DEFAULT SYSDATE()
	, BOARD_NUM INT  NOT NULL REFERENCES BOARD(BOARD_NUM)
);

SELECT *  from board;
SELECT *  from board_member;

INSERT INTO board_member(
	MEM_ID
	, MEM_PW
	, MEM_NAME
) VALUES(
	'java'
	, 'java1234'
	, '김자바'
);

INSERT INTO board(
TITLE
,CONTENT
) VALUES(
	'안녕'
	, '안녕녕영'
)

SELECT *  from board_reply;

UPDATE board_member
	SET
	,MEM_ROLE = 'ADMIN'
WHERE MEM_ID = 'admin';


#한 페이지 10개씩 조회(LIMIT), 0개 제외(OFFSET)
#1페이지는 0개 제외-> 1페이지 10개, 2페이지 20개
SELECT *  
from board
ORDER BY BOARD_NUM DESC
LIMIT 10 OFFSET 0;


SELECT 
COUNT(BOARD_NUM) 
FROM board;

SELECT * FROM EMP;
SELECT COUNT(EMPNO), COUNT(ENAME), COUNT(COMM), COUNT(*) FROM emp;   #NULL값 제외 카운트한다~~

#비동기 학습용 프로젝트 테이블
#학급정보 테이블
CREATE TABLE CLASS_INFO(
	CLASS_NO INT PRIMARY KEY AUTO_INCREMENT
	, CLASS_NAME VARCHAR(20) NOT NULL UNIQUE
);

INSERT INTO CLASS_INFO VALUES(1,'자바반');
INSERT INTO CLASS_INFO VALUES(2,'영상반');
INSERT INTO CLASS_INFO VALUES(3,'회계반');

#학생 테이블
CREATE TABLE STUDENT_INFO(
	STU_NUM INT PRIMARY KEY AUTO_INCREMENT
	, STU_NAME VARCHAR(20) NOT NULL
	, STU_AGE INT
	, CLASS_NO INT NOT NULL REFERENCES CLASS_INFO(CLASS_NO)
);

INSERT INTO STUDENT_INFO VALUES
	(1,'김자바', 20, 1)
	,(2,'이자바', 30, 1)
	,(3,'박자바', 40, 1)
	,(4,'김영상', 20, 2)
	,(5,'이영상', 30, 2)
	,(6,'박영상', 40, 2)
	,(7,'김회계', 20, 3)
	,(8,'이회계', 30, 3)
	,(9,'박회계', 40, 3);

#점수정보 테이블

CREATE TABLE SCORE_INFO(
	SCORE_NO INT PRIMARY KEY AUTO_INCREMENT
	, TEST_TYPE VARCHAR(10) NOT NULL #'중간', '기말'
	, KOR_SCORE INT 
	, ENG_SCORE INT
	, STU_NUM INT NOT NULL REFERENCES STUDENT_INFO(STU_NUM)
);

INSERT INTO SCORE_INFO VALUES
	(1, '중간', 70, 90, 1)
	, (2, '기말', 80, 90, 1)
	, (3, '중간', 80, 80, 2)
	, (4, '기말', 100, 100, 2);
	
	
#학생의 학번, 이름, 나이, 소속된 학급명 조회
SELECT 
	STU_NUM
	, STU_NAME
	, STU_AGE
	, CLASS_NAME
FROM student_info S 
INNER JOIN class_info C
ON S.CLASS_NO = C.CLASS_NO;

SELECT * FROM SCORE_INFO;

SELECT
S.STU_NUM
, STU_NAME
, STU_AGE
, S.CLASS_NO
, CLASS_NAME
, TEST_TYPE
, KOR_SCORE
, ENG_SCORE
FROM student_info S
INNER JOIN class_info C
ON S.CLASS_NO = C.CLASS_NO
INNER JOIN SCORE_INFO SCO
ON S.STU_NUM = SCO.STU_NUM
WHERE S.STU_NUM = 1;

#부서정보 테이블
CREATE TABLE DEPT_INFO(
	DEPT_NO INT PRIMARY KEY AUTO_INCREMENT
	, DEPT_NAME VARCHAR(20) NOT NULL UNIQUE
);

INSERT INTO DEPT_INFO VALUES(1, '영업부');
INSERT INTO DEPT_INFO VALUES(2, '개발부');

#직급정보 테이블
CREATE TABLE JOB_INFO(
	JOB_NO INT PRIMARY KEY AUTO_INCREMENT
	, JOB_NAME VARCHAR(10) NOT NULL UNIQUE
);

INSERT INTO JOB_INFO VALUES (1, '사원');
INSERT INTO JOB_INFO VALUES (2, '주임');

#사원정보 테이블
CREATE TABLE ENP_INFO(
	EMP_NO INT PRIMARY KEY AUTO_INCREMENT
	, EMP_NAME VARCHAR(20) NOT NULL
	, GENDER VARCHAR(10) NOT NULL  #'MALE' 'FEMALE'
	, HIRE_DATE DATETIME
	, DEPT_NO INT NOT NULL REFERENCES DEPT_INFO(DEPT_NO)
	, JOB_NO INT NOT NULL REFERENCES JOB_INFO(JOB_NO)
);




SELECT * FROM dept_info
WHERE dept_name = '마케팅부';

SELECT * FROM enp_info;


DELETE FROM enp_info
WHERE EMP_NO = 8;

DELETE FROM enp_info
WHERE EMP_NO = 3;

DELETE FROM enp_info
WHERE EMP_NO = 4;

DELETE FROM enp_info
WHERE EMP_NO = 5;

 INSERT INTO
    ENP_INFO (
    DEPT_NO
      , JOB_NO
      , EMP_NAME
      , GENDER
      , HIRE_DATE
    ) VALUES(
      2
      , 2
      , '고길동'
      , 'FEMALE'
      , '2026-08-19'
    );
    
    
select
EMP_NO
, EMP_NAME
, GENDER
, HIRE_DATE
, D.DEPT_NAME
, J.JOB_NAME
FROM ENP_INFO E
INNER JOIN  JOB_INFO J
ON E.JOB_NO = J.JOB_NO
INNER JOIN DEPT_INFO D
ON E.DEPT_NO = D.DEPT_NO;


SELECT EMP_NO
, EMP_NAME
, GENDER
, HIRE_DATE
, DEPT_NAME
, JOB_NAME
FROM ENP_INFO E, dept_info D, job_info J
WHERE E.DEPT_NO = D. DEPT_NO
AND E.JOB_NO = J.JOB_NO;

SELECT
	EMP_NO
	, EMP_NAME
	, GENDER
	, HIRE_DATE
	, D.DEPT_NAME
	, J.JOB_NAME
FROM ENP_INFO E
INNER JOIN  JOB_INFO J
ON E.JOB_NO = J.JOB_NO
INNER JOIN DEPT_INFO D
ON E.DEPT_NO = D.DEPT_NO
WHERE EMP_NAME LIKE CONCAT('%', '고' ,'%')
AND HIRE_DATE <= '2026-08-19'
AND HIRE_DATE >= '2026-08-01'
AND GENDER = 'FEMALE'
AND D.DEPT_NO = 2;



